### ISSUE TITLE
`there is no package called ‘rcmdcheck’` in github workflows for development version of ubuntu 20.04?

### ISSUE THREAD

**Issue by ajdamico** [r-lib/rcmdcheck#180]
hi Gábor, sorry if i'm overlooking something obvious..  `rcmdcheck` isn't loading on the development ubuntu cran checks on github.  everything appears fine in the release versions of mac/windows/linux, but not the upcoming linux?  CRAN accepted the package despite github's cran check failure, so this might be broader than my R package but not sure where/how this build failure ought to be fixed?  thanks for your time  :-)

https://github.com/ajdamico/convey/actions/runs/2234672040

**Comment by gaborcsardi** [comment]
This is not an rcmdcheck issue. It was not installed on your build, because a system library was missing: https://github.com/ajdamico/convey/runs/6250886929?check_suite_focus=true#step:8:3899

I suggest you use the the `v2` version of r-lib/actions, see https://github.com/r-lib/actions#releases-and-tags and so the examples in that repo.

**Comment by ajdamico** [comment]
hi Gábor, switching `v1` to `v2` in `R-CMD-check.yaml` seems to have solved it, thanks for pointing me to the problem!

https://github.com/ajdamico/convey/commit/b0a66f7ed525902e6993e47cb2dcf76d415c80d4
