### ISSUE TITLE
Check with minimum stated version of dependency packages

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#50]
i.e. to confirm that you have correctly captured the dependent version of packages in your DESCRIPTION.

(This likely will have to wait until pkgdepends + pkginstall are further developed)

**Comment by gaborcsardi** [comment]
This is a good idea, although, together with #64, they give a new angle to rcmdcheck, because currently it is not manipulating the library path at all. 

I wonder if this should be addressed in something like renv or pak. I.e. there you could easily 
- delete the private library and then install only the hard dependencies.
- delete the private library and install the minimum versions of all dependencies. 

(Well, the second is not so simple currently, but support for this could be added to renv or pak.)

But in general I would not mind having this in rcmdcheck, either. For that, I'd wait until pkgdepends in published.

**Comment by hadley** [comment]
Similarly this no longer feels like it belongs in rcmdcheck, but instead is some combination of pak + r-lib/actions.
