### ISSUE TITLE
Extract testthat test object

### ISSUE THREAD

**Issue by noamross** [r-lib/rcmdcheck#67]
For packages using *testthat* it would be helpful to have way to extract the test report object from the results of `rcmdcheck()`.  This would let one inspect and use the test results in detail without re-running the tests.

**Comment by gaborcsardi** [comment]
This would be cool indeed, but it is not possible currently. `testthat.R` or testthat itself would need to write out the results to a file. Otherwise they are lost during `R CMD check`.

Some reporters already write the output to file, and maybe the check reporter could do the same?
@hadley ?  @jimhester ?

In theory rcmdcheck could patch the `testthat.R` file, and this would work as long as the file has the standard content, but probably fail otherwise.

**Comment by jimhester** [comment]
I think having the check reporter write the test results to a file makes sense. We should open a testthat issue

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/testthat/issues/795

**Comment by gaborcsardi** [comment]
I'll close this one for now.
